services:
  cache_context_debug:
    class: Drupal\Console\Command\Cache\CacheContextDebugCommand
    tags:
      - { name: console.command }
  cache_rebuild:
    class: Drupal\Console\Command\Cache\CacheRebuildCommand
    tags:
      - { name: console.command }
