services:
  chain:
    class: Drupal\Console\Command\Chain\ChainCommand
    arguments: ['@console.file_util','@filesystem', '@parser', '@console.chain_queue']
    tags:
      - { name: console.command }
  chain_debug:
    class: Drupal\Console\Command\Chain\ChainDebugCommand
    tags:
      - { name: console.command }
