services:
  create_nodes:
    class: Drupal\Console\Command\Create\NodesCommand
    arguments: ['@console.drupal_api', '@console.create_node_data']
    tags:
      - { name: console.command }
#  create_comments:
#    class: Drupal\Console\Command\Create\CommentsCommand
#    tags:
#      - { name: console.command }
#  create_terms:
#    class: Drupal\Console\Command\Create\TermsCommand
#    tags:
#      - { name: console.command }
#  create_users:
#    class: Drupal\Console\Command\Create\UsersCommand
#    tags:
#      - { name: console.command }
#  create_vocabularies:
#    class: Drupal\Console\Command\Create\VocabulariesCommand
#    tags:
#      - { name: console.command }
