services:
  console.create_nodes:
    class: Drupal\Console\Command\Create\NodesCommand
    arguments: ['@console.drupal_api', '@console.create_node_data']
    tags:
      - { name: console.command }
  console.create_comments:
    class: Drupal\Console\Command\Create\CommentsCommand
    arguments: ['@console.create_comment_data']
    tags:
      - { name: console.command }
  create_terms:
    class: Drupal\Console\Command\Create\TermsCommand
    arguments: ['@console.create_term_data']
    tags:
      - { name: console.command }
#  create_users:
#    class: Drupal\Console\Command\Create\UsersCommand
#    tags:
#      - { name: console.command }
#  create_vocabularies:
#    class: Drupal\Console\Command\Create\VocabulariesCommand
#    tags:
#      - { name: console.command }
