services:
  console.cron_debug:
    class: Drupal\Console\Command\Cron\DebugCommand
    arguments: ['@module_handler']
    tags:
      - { name: console.command }
  console.cron_execute:
    class: Drupal\Console\Command\Cron\ExecuteCommand
    arguments: ['@module_handler', '@state', '@lock', '@console.chain_queue']
    tags:
      - { name: console.command }
#  cron_release:
#    class: Drupal\Console\Command\Cron\ReleaseCommand
#    tags:
#      - { name: console.command }
