services:
  console.database_client:
    class: Drupal\Console\Command\Database\ClientCommand
    tags:
      - { name: console.command }
  console.database_connect:
    class: Drupal\Console\Command\Database\ConnectCommand
    tags:
      - { name: console.command }
  console.database_drop:
    class: Drupal\Console\Command\Database\DropCommand
    arguments: ['@database']
    tags:
      - { name: console.command }
  console.database_dump:
    class: Drupal\Console\Command\Database\DumpCommand
    arguments: ['@app.root', '@console.shell_process']
    tags:
      - { name: console.command }
#  database_log_clear:
#    class: Drupal\Console\Command\Database\LogClearCommand
#    tags:
#      - { name: console.command }
#  database_log_debug:
#    class: Drupal\Console\Command\Database\LogDebugCommand
#    tags:
#      - { name: console.command }
  console.database_restore:
    class: Drupal\Console\Command\Database\RestoreCommand
    tags:
      - { name: console.command }
  console.database_table_debug:
    class: Drupal\Console\Command\Database\TableDebugCommand
    arguments: ['@console.redbean', '@database']
    tags:
      - { name: console.command }
