#services:
#  generate_doc_dash:
#    class: Drupal\Console\Command\Develop\GenerateDocDashCommand
#    tags:
#      - { name: console.command }
#  generate_doc_data:
#    class: Drupal\Console\Command\Develop\GenerateDocDataCommand
#    tags:
#      - { name: console.command }
#  generate_doc_gitbook:
#    class: Drupal\Console\Command\Develop\GenerateDocGitbookCommand
#    tags:
#      - { name: console.command }
#  generate_doc_cheatsheet:
#    class: Drupal\Console\Command\Develop\GenerateDocCheatsheetCommand
#    tags:
#      - { name: console.command }
#
