services:
  console.image_styles_debug:
    class: Drupal\Console\Command\Image\StylesDebugCommand
    arguments: ['@entity_type.manager']
    tags:
      - { name: console.command }
#  image_styles_flush:
#    class: Drupal\Console\Command\Image\StylesFlushCommand
#    tags:
#      - { name: console.command }
