services:
  translation_status:
    class: Drupal\Console\Command\Locale\TranslationStatusCommand
    tags:
      - { name: console.command }
  language_delete:
    class: Drupal\Console\Command\Locale\LanguageDeleteCommand
    tags:
      - { name: console.command }
  language_add:
    class: Drupal\Console\Command\Locale\LanguageAddCommand
    tags:
      - { name: console.command }
