services:
  console.container_debug:
    class: Drupal\Console\Command\ContainerDebugCommand
    tags:
      - { name: console.command }
      - { name: console.drupal_installed }
  console.plugin_debug:
    class: Drupal\Console\Command\PluginDebugCommand
    tags:
      - { name: console.command }
      - { name: console.drupal_installed }
  console.server:
    class: Drupal\Console\Command\ServerCommand
    arguments: ['@app.root', '@console.configuration_manager']
    tags:
      - { name: console.command }
  console.event_debug:
    class: Drupal\Console\Command\EventDebugCommand
    arguments: ['@event_dispatcher']
    tags:
      - { name: console.command }
      - { name: console.drupal_installed }
#  console.devel_dumper:
#    class: Drupal\Console\Command\DumperCommand
#    arguments: ['@app.root']
#    tags:
#      - { name: console.command }
#      - { name: console.drupal_installed }
