services:
  container_debug:
    class: Drupal\Console\Command\ContainerDebugCommand
    tags:
      - { name: console.command }
  plugin_debug:
    class: Drupal\Console\Command\PluginDebugCommand
    tags:
      - { name: console.command }
  server:
    class: Drupal\Console\Command\ServerCommand
    tags:
      - { name: console.command }
  event_debug:
    class: Drupal\Console\Command\EventDebugCommand
    tags:
      - { name: console.command }
