services:
#  module_debug:
#    class: Drupal\Console\Command\Module\DebugCommand
#    tags:
#      - { name: console.command }
#  module_download:
#    class: Drupal\Console\Command\Module\DownloadCommand
#    tags:
#      - { name: console.command }
  module_install:
      class: Drupal\Console\Command\Module\InstallCommand
      arguments: ['@console.chain_queue', '@console.shell_process', '@module_installer', '@console.drupal_api', '@console.validator', '@console.extension_manager']
      tags:
        - { name: console.command }
  module_path:
      class: Drupal\Console\Command\Module\PathCommand
      arguments: ['@console.site']shell_process
      tags:
        - { name: console.command }
  module_update:
    class: Drupal\Console\Command\Module\UpdateCommand
    arguments: ['@console.shell_process']
    tags:
      - { name: console.command }
  module_uninstall:
    class: Drupal\Console\Command\Module\UninstallCommand
    arguments: ['@console.chain_queue', '@console.shell_process', '@module_installer', '@console.drupal_api', '@config.factory']
    tags:
      - { name: console.command }
