services:
  test_debug:
    class: Drupal\Console\Command\Test\DebugCommand
    arguments: ['@test_discovery']
    tags:
      - { name: console.command }
  test_run:
    class: Drupal\Console\Command\Test\RunCommand
    arguments: ['@console.site', '@test_discovery', '@module_handler'. '@date.formatter']
    tags:
      - { name: console.command }
