services:
  test_debug:
    class: Drupal\Console\Command\Test\DebugCommand
    tags:
      - { name: console.command }
  test_run:
    class: Drupal\Console\Command\Test\RunCommand
    arguments: ['test_discovery', '@console.site']
    tags:
      - { name: console.command }
