services:
  console.update_debug:
     class: Drupal\Console\Command\Update\DebugCommand
     arguments: ['@console.drupal_api', '@update.post_update_registry']
     tags:
        - { name: console.command }
  console.update_entities:
    class: Drupal\Console\Command\Update\EntitiesCommand
    arguments: ['@state', '@entity.definition_update_manager', '@console.chain_queue']
    tags:
      - { name: console.command }
  console.update_execute:
    class: Drupal\Console\Command\Update\ExecuteCommand
    arguments: ['@console.drupal_api', '@state', '@module_handler', '@update.post_update_registry', '@console.chain_queue']
    tags:
      - { name: console.command }