services:
  views_disable:
    class: Drupal\Console\Command\Views\DisableCommand
    arguments: ['@entity_type.manager', '@entity.query']
    tags:
      - { name: console.command }
  views_enable:
    class: Drupal\Console\Command\Views\EnableCommand
    arguments: ['@entity_type.manager', '@entity.query']
    tags:
      - { name: console.command }
  views_debug:
    class: Drupal\Console\Command\Views\DebugCommand
    arguments: ['@entity_type.manager']
    tags:
      - { name: console.command }
  views_plugins_debug:
    class: Drupal\Console\Command\Views\PluginsDebugCommand
    tags:
      - { name: console.command }
