sudo: false

language: php

php:
  - 5.6
  #- 7.0
  - 7.1
  #- 7.2
  #- 7.3
  #- 7.4snapshot

matrix:
#  include:
#    - php: 5.5.9
#      dist: trusty
  fast_finish: true
  allow_failures:
    - php: 7.4snapshot

env:
  global:
    # Paths.
    - DRUPAL_PATH="$HOME/drupal8"
    - PATH="$PATH:$DRUPAL_PATH/vendor/bin:$HOME/.composer/vendor/bin"

    # Testing environment variables.
    - SIMPLETEST_DB=sqlite://localhost/sites/default/files/.ht.sqlite
    - SIMPLETEST_BASE_URL=http://127.0.0.1:8080

    # Suppress deprecation handling.
    #- SYMFONY_DEPRECATIONS_HELPER=disabled

before_script:
  - phpenv config-rm xdebug.ini || true
  # This fixes a fail when install Drupal.
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  - git clone --depth=50 http://git.drupal.org/project/drupal.git $DRUPAL_PATH
  - cd $DRUPAL_PATH
  - git checkout 8.8.x
  - composer install --no-dev --no-progress --no-suggest
  - composer require "drupal/console:dev-master" --no-progress --no-suggest

  # Replace vendor/console with cloned one.
  #- ls $DRUPAL_PATH/vendor/drupal
  #- ls $DRUPAL_PATH/vendor/drupal/console
  #- rm -rf $DRUPAL_PATH/vendor/drupal/console
  #- mkdir -p $DRUPAL_PATH/vendor/drupal/console
  #- cp -r $HOME/build/mondrake/drupal-console $DRUPAL_PATH/vendor/drupal
  #- mv $DRUPAL_PATH/vendor/drupal/drupal-console $DRUPAL_PATH/vendor/drupal/console
  #- ls $DRUPAL_PATH/vendor/drupal
  #- ls $DRUPAL_PATH/vendor/drupal/console

  - drupal server 127.0.0.1:8080 &

script:
  - drupal site:install standard $SIMPLETEST_DB --langcode=en --site-name="Drupal 8 Site Install" --site-mail=admin@example.com --account-name=admin --account-mail=admin@example.com --account-pass=admin --no-interaction
  - drupal site:status
#  - phpunit
#  - ~/.composer/vendor/bin/phpcs --warning-severity=0 --standard=~/.composer/vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml $PROJECT_DIR/drupal8.dev/modules/custom/example

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/637685414a0d0ef9d4c6
    on_success: change
    on_failure: always
