language: php

php:
  - 5.4
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install --no-dev
  - curl -LSs https://box-project.github.io/box2/installer.php | php
  - composer global require drush/drush:dev-master
  - composer global require drupal/coder:~8.1

script:
  - phpunit
  - php box.phar build
  - php console.phar --version
  - sudo mv console.phar /usr/local/bin/drupal
  - ~/.composer/vendor/bin/drush dl drupal-8.0.0-beta9
  - mv drupal-8.0.0-beta9 drupal8.dev
  - cd drupal8.dev
  - ~/.composer/vendor/bin/drush site-install standard --yes --account-name=root --account-pass=toor --db-url=sqlite:$TRAVIS_BUILD_DIR/drupal8.dev/sites/default/files/console.sqlite
  - drupal chain --file=$TRAVIS_BUILD_DIR/config/dist/chain.yml
  - ~/.composer/vendor/bin/phpcs --standard=~/.composer/vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml modules/custom/example
  - if ~/.composer/vendor/bin/phpcs --standard=~/.composer/vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml modules/custom/example | egrep "FOUND ([1-9]+) ERRORS" --quiet; then echo "Errors in coding standards"; exit 1; else exit 0; fi

after_script:
  - rm -r /tmp/modules

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/637685414a0d0ef9d4c6
    on_success: change
    on_failure: always