language: php

php:
  - 5.4
  - 5.6

before_script:
  - composer install --dev --prefer-source

after_success:
  - ./bin/phpcs --standard=vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml /tmp/modules/*
  - rm -r /tmp/modules
