application:
  environment: prod
  language: en
  editor: vi
  temp: /tmp
  develop: false
  autowire:
    commands:
      forced:
        _completion:
          class: '\Stecman\Component\Symfony\Console\BashCompletion\CompletionCommand'
          helperset: false
      name:
        elephpant:
          class: '\Drupal\Console\Command\Autowire\ElephpantCommand'
          helperset: true
