application:
  autowire:
    commands:
      forced:
        _completion:
          class: '\Stecman\Component\Symfony\Console\BashCompletion\CompletionCommand'
      name:
        elephpant:
          class: '\Drupal\Console\Command\Exclude\ElephpantCommand'
        druplicon:
          class: '\Drupal\Console\Command\Exclude\DrupliconCommand'
