requirements:
  php-version:
    required: 5.5.9
  configurations:
    required:
      - date.timezone: "America/Los_Angeles"
      - memory_limit: 1024M
    recomended:
  extensions:
    required:
      - date
      - dom
      - filter
      - gd
      - hash
      - json
      - pcre
      - pdo
      - session
      - SimpleXML
      - SPL
      - tokenizer
      - xml
      - curl
    recommended:
      - mysql
      - sqlite3
      - ssh2
