services:
  parser:
    class: Symfony\Component\Yaml\Parser
    lazy: true
  finder:
    class: Symfony\Component\Finder\Finder
    lazy: true
  filesystem:
    class: Symfony\Component\Filesystem\Filesystem
    lazy: true
  yaml:
    class: Symfony\Component\Yaml\Yaml
    lazy: true
  config:
    class: Drupal\Console\Config
    arguments: ["@parser"]
  requirement_checker:
    class: Drupal\Console\Utils\RequirementChecker
    arguments: ["@parser"]
    lazy: true
  redbean:
    class: RedBeanPHP\R
    lazy: true
  file_util:
    class: Drupal\Console\Utils\File
    lazy: true
  translator:
    class: Drupal\Console\Utils\Translator
    arguments: ["@finder", "@parser", "@filesystem"]
    lazy: true
  site:
    class: Drupal\Console\Utils\Site
    arguments: ["@finder", "@parser"]
    lazy: true
  chain:
    class: Drupal\Console\Utils\Chain
    lazy: true
  showfile:
    class: Drupal\Console\Utils\ShowFile
    arguments: ["@site", "@translator"]
    lazy: true
  about:
    class: Drupal\Console\Command\AboutCommand
    arguments: ["@translator"]
    lazy: true
    tags:
      - { name: console.command }
  check:
    class: Drupal\Console\Command\CheckCommand
    arguments: ["@translator"]
    lazy: true
    tags:
      - { name: console.command }
  complete:
    class: Drupal\Console\Command\CompleteCommand
    arguments: ["@translator"]
    lazy: true
    tags:
      - { name: console.command }
  init:
    class: Drupal\Console\Command\InitCommand
    arguments: ["@translator"]
    lazy: true
    tags:
      - { name: console.command }
  list:
    class: Drupal\Console\Command\ListCommand
    arguments: ["@translator"]
    lazy: true
    tags:
      - { name: console.command }
  help:
    class: Drupal\Console\Command\HelpCommand
    arguments: ["@translator"]
    lazy: true
    tags:
      - { name: console.command }
  server:
    class: Drupal\Console\Command\ServerCommand
    arguments: ["@translator"]
    lazy: true
    tags:
      - { name: console.command }
