services:
  console.module_generator:
    class: Drupal\Console\Generator\ModuleGenerator
    tags:
      - { name: console.generator }
  console.authentication_provider_generator:
    class: Drupal\Console\Generator\AuthenticationProviderGenerator
    arguments: ['@console.extension_manager']
    tags:
      - { name: console.generator }
  console.controller_generator:
    class: Drupal\Console\Generator\ControllerGenerator
    arguments: ['@console.extension_manager']
    tags:
      - { name: console.generator }
  console.breakpoint_generator:
    class: Drupal\Console\Generator\BreakPointGenerator
    arguments: ['@console.extension_manager']
    tags:
      - { name: console.generator }
