services:
  console.generate_breakpoint:
    class: Drupal\Console\Command\Generate\BreakPointCommand
    arguments: ['@console.breakpoint_generator', '@app.root', '@theme_handler', '@console.validator']
    tags:
      - { name: console.command }
