services:
  console.queue_debug:
    class: Drupal\Console\Command\Queue\DebugCommand
    arguments: ['@plugin.manager.queue_worker']
    tags:
      - { name: console.command }
  console.queue_run:
    class: Drupal\Console\Command\Queue\RunCommand
    arguments: ['@plugin.manager.queue_worker', '@queue']
    tags:
      - { name: console.command }
