services:
  router_debug:
    class: Drupal\Console\Command\Router\DebugCommand
    arguments: ['@router.route_provider']
    tags:
      - { name: console.command }
  console.router_rebuild:
    class: Drupal\Console\Command\Router\RebuildCommand
    arguments: ['@router.builder']
    tags:
      - { name: console.command }
