#services:
#  site_debug:
#    class: Drupal\Console\Command\Site\DebugCommand
#    tags:
#      - { name: drupal.command }
#  site_import_local:
#    class: Drupal\Console\Command\Site\ImportLocalCommand
#    tags:
#      - { name: drupal.command }
#  site_install:
#    class: Drupal\Console\Command\Site\InstallCommand
#    tags:
#      - { name: drupal.command }
#  site_maintenance:
#    class: Drupal\Console\Command\Site\MaintenanceCommand
#    tags:
#      - { name: drupal.command }
#  site_mode:
#    class: Drupal\Console\Command\Site\ModeCommand
#    tags:
#      - { name: drupal.command }
#  site_new:
#    class: Drupal\Console\Command\Site\NewCommand
#    tags:
#      - { name: drupal.command }
#  site_statistics:
#    class: Drupal\Console\Command\Site\StatisticsCommand
#    tags:
#      - { name: drupal.command }
#  site_status:
#    class: Drupal\Console\Command\Site\StatusCommand
#    tags:
#      - { name: drupal.command }
